# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  vmImage: 'macOS 10.13'

steps:
- script: |


    brew uninstall --force node
    brew prune
    rm -f /usr/local/bin/npm /usr/local/lib/dtrace/node.d
    rm -rf ~/.npm
    brew install node
    node -v
    npm -v
    echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-27;google_apis;x86'
    $ANDROID_HOME/platform-tools/adb devices
    echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n emulator-5554 -k 'system-images;android-27;google_apis;x86' --force
    brew outdated xctool || brew upgrade xctool
    xcrun simctl list -j
    npm install -g appium
    appium -v
    mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test
  displayName: 'Build with Maven'
