# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  vmImage: 'macOS 10.13'

steps:
- script: |
    echo no | android create avd --force --name emulator-5554 --abi google_apis/x86_64 --package 'system-images;android-27;google_apis;x86_64'
    brew outdated xctool || brew upgrade xctool
    xcrun simctl list -j
    npm install -g appium
    appium -v
    mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test
  displayName: 'Build with Maven'
