# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  vmImage: 'macOS 10.13'

steps:
- script: |
    brew outdated xctool || brew upgrade xctool
    xcrun simctl list -j
    npm install -g appium
    appium -v
    mvn clean install
  displayName: 'Build with Maven'