# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/node
    - image: circleci/android:api-26-alpha
version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install Appium
          command: 'sudo npm install -g appium'
      - run:
          name: Check Version
          command: appium -v
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run:
          name: Resolve dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  test:
    <<: *defaults
    steps:
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run:
          name: Wait for emulator
          command: |
            chmod +x ~/code/script/android-wait-for-boot.sh;
            ~/code/script/android-wait-for-boot.sh;
          environment:
            TERM: dumb
      - run:
          name: Run UI Tests
          command: mvn integration-test
workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - build
